version: "3.9"
services:
  ontology:
    image: docker.uibk.ac.at:443/csaw4226/sakd/ontology-service:latest
    ports:
      - "8001:8000"
#  classifier:
#    image: docker.uibk.ac.at:443/csaw4226/sakd/cassava_classifier:latest
  decision-engine:
    image: docker.uibk.ac.at:443/csaw4226/sakd/decision-service:latest
    ports:
      - "8000:8000"
    environment:
      - CLASSIFIER_SERVICE_URL=http://electricsheep:3000
      - ONTOLOGY_SERVICE_URL=http://ontology:8000
  node-red-flow:
    image: docker.uibk.ac.at:443/csaw4226/sakd/node-red:latest
    ports:
      - "1880:1880"



